apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nrpod
  labels:
spec:
  selector:
    matchLabels:
      name: nrdaemon
  template:
    metadata:
      labels:
        name: nrdaemon
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - name: nrpod
        image: busybox
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host
          name: nro
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        ports:
        - containerPort: 4444
      volumes:
      - name: nro
        hostPath:
          path: /
---
apiVersion: v1
kind: Service
metadata:
  name: busybox-shell-service
spec:
  selector:
    app: busybox
  ports:
  - protocol: TCP
    port: 4444
    targetPort: 4444
  type: NodePort
